#!/usr/bin/env sh

echo '👀 Checking commit message.'
echo ''

pnpm exec commitlint --edit "$1"
if [ $? != 0 ]; then
  echo
  echo '❌ The commit message does not conform to the correct format. Check the message format.'
  echo
  exit 1
fi
echo ''
echo '✅ Commit message checked successfully'

